steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['clean']
  
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package']
   
 - name: gcr.io/cloud-builders/docker
   args: ["build", "-t", "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA", "--build-arg=WAR_FILE=target/springboot-0.0.1-SNAPSHOT.war", "."]
   
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA']

 - name: "gcr.io/cloud-builders/gke-deploy"
   args:
   - run
   - --filename=springdeployment.yaml
   - --location=us-central1-c
   - --cluster=cloudbuildgke