apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdeploy
spec:
  selector:
    matchLabels:
      app: springapp
  replicas: 2
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
      - name: springboot
        image: gcr.io/eternal-ship-281907/springapp	
        ports:
        - containerPort: 8080
        
---

apiVersion: v1
kind: Service
metadata:
  name: springservice
spec:
  loadBalancerIP: 35.184.57.24
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: springapp
    
    
---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: spring-ingress
spec:
  backend:
    serviceName: springservice
    servicePort: 80