apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdeploy
spec:
  selector:
    matchLabels:
      app: springapp
  replicas: 2
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
      - name: springboot
        image: gcr.io/eternal-ship-281907/springapp
        ports:
        - containerPort: 8080
        ...
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 2
          periodSeconds: 8
          failureThreshold: 1
        
---

apiVersion: v1
kind: Service
metadata:
  name: springservice
spec:
  loadBalancerIP: 35.184.57.24
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: springapp
    
   